### ISSUE TITLE
Xenon CPU Specification

### ISSUE THREAD

**Issue by akmubi** [Hect0rLeManiac/Xenious#1]
Why are the registers 32-bit? (Xenious/XenonPowerPC/CPU/XenonCPU.cs)
I thought that they're 64-bit. [ [Xbox 360 Architecture.pptx](http://meseec.ce.rit.edu/551-projects/spring2013/2-3.pdf) ] - (11th slide)

**Comment by akmubi** [comment]
Finally found source – [The Microsoft Xbox 360 CPU story](https://www.webcitation.org/65roY0m2F?url=http://www.ibm.com/developerworks/power/library/pa-fpfxbox/)

**Comment by XmodsProject** [comment]
couldent agree more, in the process of fixing all the bugs, I just got rijndael decryption and encryptionm working, I wanted to post a complete build but this is as far as I got in the last hour with the latest release.

I will get this fixed @akmubi thanks for the heads up, I originally thought the registers where 32bit in general, with 64 bit floating points.

Anyway give me a few more hours and ill have powerpc formats from the docs I found and am currently reversing the format from the specs :)

 - Jed

**Comment by XmodsProject** [comment]
https://github.com/XenProject/Xenious/commit/6b3a1edb86a4fb52ce31ecb2110a50c1ad6d3c6d

**Comment by akmubi** [comment]
Are you reversing XEX format?

**Comment by mirh** [comment]
There are [other tools](https://github.com/emoose/idaxex) for that too.

**Comment by XmodsProject** [comment]
> Are you reversing XEX format?

I am in some parts, I have things in my brain I remember and Im still understanding, ill have a more up to date build of my research somepoint this month I hope if time permits.

Im actually looking at ISA specifications to understand the OPCode or assembler structure in power pc.
PS Thanks for the tip I hadent even looked at that part of the code in XenonPowerPC library in a while I was just removing and updating things so I could build something to work from, I left the original code full of bugs and idiotic code I was learning at the time.



> There are [other tools](https://github.com/emoose/idaxex) for that too.

There are, however only problem is, unless you have access to a decent pirated copy or can fork out the many pennys / cents for the program and its associated license terms.

I plan to make this a free disassembler, so people dont have to pay the ida fee or risk a rat from using a pirated version, give me time i m working on this when I get time ;)
